# .github/workflows/ci.yml

name: Code Quality and Testing

# This action will run on every 'push' to the main branch,
# and on every 'pull request' that targets the main branch.
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    # We'll use the latest version of Ubuntu Linux to run our checks.
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checks out a copy of your repository's code.
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Sets up a Python environment.
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'

      # Step 3: Installs our project's dependencies.
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install black pytest tensorflow

      # Step 4: Run the 'black' linter to check code formatting.
      - name: Lint with black
        run: |
          black . --check

      # Step 5: Run the 'pytest' framework to run all our unit tests.
      - name: Test with pytest
        run: |
          pytest